name: final_assignment_si
description: "Programming"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.16
  flutter_swipe_button: ^2.1.3
  ticket_widget: ^1.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0


flutter:

  assets:
    - assets/
    - assets/links/

  uses-material-design: true
